#!/bin/bash
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

echo "Starting build."
BUILD_ERRORS=$(gulp build 2>&1 >/dev/null)
if ! [ $? == 0 ]
then
    echo -e "\n${red}Build failed - ABORT COMMIT!${no_color}\n"
    exit 1
fi
echo -e "\n${green}Build successful.${no_color}"

echo "Starting tests."
gulp test &> /dev/null
if ! [ $? == 0 ]
then
    echo -e "\n${red}Tests failed - ABORT COMMIT!${no_color}\n"
    exit 1
fi
echo -e "\n${green}Tests successful.${no_color}"

echo "Starting lint."
LINT_ERRORS=$(gulp lint | grep 'error')
if ! [ -z "$LINT_ERRORS" ];
then
    echo -e "\n${yellow}WARN: Linting failed!${no_color}\n"
    echo $LINT_ERRORS
else
    echo -e "\n${green}Linting successful.${no_color}"
fi

echo -e "\n${green}COMMIT successful.${no_color}"
